Fix #102 - Update Part2 Step17 to match new requirements
SolidDesignNet/j1939-84 pull request #113
Opened 2022-05-12 15:23 UTC by mmschaefer

2022-05-16 01:00 UTC, gumbelmj requested changes

2022-05-16 01:00 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part02/Part02Step17Controller.java
> +        // @Joe we just need a method to call here. Eric added a column to Table A-1, I believe; please double check me
The method already exists.  It's `TableA1Validator.reportProvidedButNotSupportedSPNs()`

2022-05-16 01:00 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part02/Part02Step17Controller.java
> +                               // SAE INTERNATIONAL J1939TM-84 Proposed Draft 24 March
Please remove the cruft.

2022-05-16 01:00 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part02/Part02Step17Controller.java
> +                               // @Joe - just need to add the call once the dataRepo bug is fix
Is there a ticket filed for this bug?

2022-05-16 23:23 UTC, mmschaefer commented on src/org/etools/j1939_84/controllers/part02/Part02Step17Controller.java
> +                               // @Joe - just need to add the call once the dataRepo bug is fix
https://github.com/SolidDesignNet/j1939-84/issues/117

2022-05-17 10:38 UTC, gumbelmj requested changes

2022-05-17 10:38 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part02/Part02Step17Controller.java
> +                                   .filter(obdModuleInformation -> {
This filter is redundant with the checks below.

2022-05-17 10:38 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part02/Part02Step17Controller.java
> +        onRequestPackets.stream()
`.stream()` is not necessary here.

2022-05-17 10:38 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part02/Part02Step17Controller.java
> +                               // if (spn.getRawValue() >= 0xFAFFL) {
Why is this code commented out?

2022-05-17 10:38 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part02/Part02Step17Controller.java
> +                               // 6.2.17.20.c - Fail all values where the corresponding values received
The rest of the text is missing here.

2022-05-17 10:38 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part02/Part02Step17Controller.java
> +                                           addFailure("6.1.26.14.c - Bin value received is greater than 0xFAFF from "
Section number is wrong here.

2022-05-17 10:38 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part02/Part02Step17Controller.java
> +                                   addFailure("6.2.17.18.c - PG query index received was " + "");
Section number is wrong here.

2022-05-17 10:38 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part02/Part02Step17Controller.java
> +                        addWarning("6.2.17.10.d - Active 100 hr array bin 3 through bin 17 values received has a value greater than zero (where supported) from "
Please condense this text.

2022-05-17 15:10 UTC, gumbelmj approved these changes
There are two minor changes that need resolved and then you can merge it.

2022-05-17 15:10 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part02/Part02Step17Controller.java
> +                               addFailure("6.1.26.20.b - Bin value received is greater than 0xFAFFFFFF(h) from "
Section number is wrong.

2022-05-17 15:10 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part02/Part02Step17Controller.java
> +                                   addFailure("6.2.17.18.d - PG query index received was " + "");
The rest of this failure message is missing.

2022-05-18 18:10 UTC, merged