Updates/verification to 6/24/2021 requirements
SolidDesignNet/j1939-84 pull request #38
Opened 2021-09-15 15:35 UTC by mmschaefer

Fix #33 - Update Part01Step14Controller.java and [Part01Step14ControllerTest.java.](url)  Logic was modified and tests were added and updated to match  latest spec issued 6/24/2021 updates.  Documentation of both files were updated as well.

2021-09-21 17:21 UTC, gumbelmj requested changes

2021-09-21 17:21 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part01/Part01Step14Controller.java
> +                                 && !dm26System.getStatus().isEnabled();
The `!` shouldn’t be here.

2021-09-21 17:21 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part01/Part01Step14Controller.java
> +                         addFailure("6.1.14.2.d - " + moduleName + " indicates support for " + systemName
The text doesn’t match the requirement

2021-09-23 14:09 UTC, mmschaefer commented
Fixed

2021-09-23 18:32 UTC, gumbelmj approved these changes

2021-09-23 18:47 UTC, merged